name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to Sandbox
        run: |
          echo "${{ secrets.SF_JWT_PRIVATE_KEY }}" > server.key
          sf org login jwt --client-id ${{ secrets.SF_CONSUMER_KEY }} \
                          --jwt-key-file server.key \
                          --username ${{ secrets.SF_SANDBOX_USERNAME }} \
                          --instance-url ${{ secrets.SF_LOGIN_URL }} \
                          --set-default

      - name: Validate Metadata
        run: |
          sf project deploy validate --source-dir force-app \
                                    --test-level RunLocalTests \
                                    --wait 30

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to Production
        run: |
          echo "${{ secrets.SF_JWT_PRIVATE_KEY }}" > server.key
          sf org login jwt --client-id ${{ secrets.SF_CONSUMER_KEY }} \
                          --jwt-key-file server.key \
                          --username ${{ secrets.SF_USERNAME }} \
                          --instance-url ${{ secrets.SF_LOGIN_URL }} \
                          --set-default

      - name: Deploy to Production
        run: |
          sf project deploy start --source-dir force-app \
                                 --test-level RunLocalTests \
                                 --wait 30