name: Deploy to Production

on:
  push:
    branches:
      - master
    paths:
      - 'force-app/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || 'master' }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Debug Secrets
        run: |
          echo "SF_CONSUMER_KEY length: ${#SF_CONSUMER_KEY}"
          echo "SF_USERNAME: ${SF_USERNAME}"
          echo "SF_LOGIN_URL: ${SF_LOGIN_URL}"
        env:
          SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_LOGIN_URL: ${{ secrets.SF_LOGIN_URL }}

      - name: Authenticate to Production
        run: |
          echo "${{ secrets.SF_JWT_PRIVATE_KEY }}" > server.key
          sf org login jwt --client-id ${{ secrets.SF_CONSUMER_KEY }} \
                          --jwt-key-file server.key \
                          --username ${{ secrets.SF_USERNAME }} \
                          --instance-url ${{ secrets.SF_LOGIN_URL }} \
                          --set-default

      - name: Deploy to Production
        run: |
          sf project deploy start --source-dir force-app \
              --test-level RunLocalTests \
              --wait 300 \
              --ignore-conflicts